### ISSUE TITLE
SyntaxError: invalid syntax on running multidl

### ISSUE THREAD

**Issue by dalmia** [julienc91/multidl#5]
Hello. I get the following error on using `multidl`. Please let me know what changes need to be made.

```python
Traceback (most recent call last):
  File "/usr/local/bin/multidl", line 9, in <module>
    load_entry_point('multidl==0.1', 'console_scripts', 'multidl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/multidl/cli.py", line 7, in <module>
  File "/usr/local/lib/python2.7/dist-packages/multidl-0.1-py2.7.egg/multidl/download_manager.py", line 36
    print(*args, **kwargs)
          ^
SyntaxError: invalid syntax

```

**Comment by julienc91** [comment]
You must use python 3.4 or newer, `multidl` is not compatible with python 2. I should probably add this somewhere in the README...

**Comment by dalmia** [comment]
Yup! That would be helpful, thanks!

**Comment by peihsendoyle** [comment]
Could you show me how to switch from python2 to python3?
